name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy PyGithub
      
      - name: Generate Snake Graph
        run: |
          python generate_snake.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'nitishrudra3510'
          git config --global user.email 'nitishrudra3510@gmail.com'
          git add contributions.png
          git commit -m 'Generated snake graph'
          git push
